export const SCENARIOS = {
  home: {
    initializing: {
      title: "正在整理小宇的成长线索",
      reason: "刚完成同步，需要一点时间把新片段整理好。",
      next: "先去忙一会儿，整理完成后会在首页告诉你。",
      recovery: "稍后回来查看",
    },
    empty: {
      title: "从今天的一小步开始",
      reason: "还没有足够的学习片段，暂时不生成成长判断。",
      next: "等小宇完成一次学习后，再回来看看。",
      recovery: "查看记录方式",
    },
    ready: {
      title: "小宇正在把好奇心说出来",
      reason: "最近 7 天的学习片段里，问题和自己的猜想变多了。",
      next: "今晚和小宇聊一个小问题。",
      recovery: "查看最近 7 天",
      action: "如果能去一个星球，你会带什么？",
    },
    stale: {
      title: "先看上次整理好的成长线索",
      reason: "设备暂时没有回传最新片段，页面保留上次内容。",
      next: "让小宇的设备保持联网，再试一次同步。",
      recovery: "重新同步",
      updatedAt: "上次更新：2026年8月20日 08:42",
    },
    locked: {
      title: "解锁完整的成长陪伴",
      reason: "当前方案可以查看基础摘要，完整周报和更多陪伴建议属于升级权益。",
      next: "查看方案差异，再按需要决定。",
      recovery: "查看会员方案",
    },
    error: {
      title: "暂时没能更新首页",
      reason: "刚才同步没有完成，我们保留了安全缓存，不影响你继续陪伴小宇。",
      next: "检查网络后再试一次。",
      recovery: "重新尝试",
      cachedAt: "安全缓存 · 2026年8月20日 09:12",
      cachedSummary: "小宇最近在关注星空和“时间”，自己的猜想变多了。",
    },
  },
  plans: {
    monthly: { price: 138, parentFullAccess: false },
    quarterly: { price: 368, parentFullAccess: false },
    annual: { price: 988, parentFullAccess: true },
  },
  parentProfile: {
    parentNickname: "小宇家长",
    parentInitial: "宇",
    parentPhone: "138****8888",
    childName: "小宇",
    childAge: 10,
    childInitial: "宇",
    interests: ["星空", "时间"],
    temperament: "好奇",
    learningPreference: "喜欢先猜一猜",
    device: "Android Pad",
    deviceStatus: "已连接",
  },
  parentGrowth: {
    level: "L3",
    title: "回应型家长",
    stage: "尝试回应",
    points: 68,
    target: 100,
    monthlyChange: 8,
    remaining: 32,
    period: "最近 90 天",
    percentile: 35,
    percentileCopy: "成长进度超过 35% 的同阶段家庭",
    dimensions: [
      { label: "学习方法", value: 72, evidence: "完成 3 节定制课，并留下 2 次课后回应" },
      { label: "亲子行动", value: 64, evidence: "完成 4 次亲子行动，其中 2 次做了复盘" },
      { label: "互动回应", value: 70, evidence: "孩子有 3 次主动把想法讲给你听" },
      { label: "复盘调整", value: 58, evidence: "记录过 2 次行动后的感受和调整" },
      { label: "持续性", value: 61, evidence: "最近 90 天在 12 个不同日期有陪伴记录" },
    ],
    nextAction: {
      title: "完成一次行动复盘",
      body: "行动结束后，用一分钟记下孩子的反应和你下次想换的做法。",
      cta: "去做本月行动",
    },
  },
  settings: {
    groups: [
      {
        label: "账号与家庭",
        items: [
          { screen: "account-security", title: "账号与安全", description: "手机号、登录密码和登录设备" },
          { screen: "child-profile", title: "孩子与设备", description: "孩子资料、兴趣偏好和孩子端设备" },
        ],
      },
      {
        label: "陪伴偏好",
        items: [
          { screen: "notification-settings", title: "通知与活动建议", description: "通知、安静时段和位置权限" },
          { screen: "privacy-settings", title: "隐私与授权", description: "查看数据范围和授权管理" },
        ],
      },
      {
        label: "需要帮助",
        items: [
          { screen: "help-feedback", title: "帮助与反馈", description: "常见问题、联系客服和意见反馈" },
        ],
      },
    ],
  },
  agent: {
    example: {
      privacy: "summary-only",
      question: "最近总在追问睡觉和时间，我该怎么陪他聊？",
      evidence: "近期学习片段中，他更常先提出自己的猜想，再寻找答案。",
      suggestion: "先请他猜一猜身体休息时会发生什么，再一起补充答案。",
    },
  },
  activity: {
    privacy: "summary-only",
    range: "最近 7 天",
    updatedAt: "刚刚整理",
    summary: "小宇最近 7 天有 4 天参与活动，常回到星空和时间。",
    stats: [
      { label: "参与", value: "4 天", note: "有活动记录" },
      { label: "活动", value: "6 次", note: "课程与亲子探索" },
      { label: "兴趣", value: "星空 · 时间", note: "最近常出现" },
    ],
    change: {
      title: "开始先说自己的猜想",
      body: "他会先讲自己的想法，再去听答案。",
      evidence: "来自 3 个活动摘要",
    },
    recent: [
      { type: "课程", date: "3 天前", title: "星光要走多久才到我们这里？", result: "听完音频并看了配图", icon: "✦" },
      { type: "亲子行动", date: "1 天前", title: "睡前猜一猜", result: "和家人完成一次三步探索", icon: "↗" },
      { type: "探索", date: "昨天", title: "影子会不会帮我们记时间？", result: "留下一个想继续验证的问题", icon: "◒" },
    ],
    next: "如果能去一个星球，你想带什么？",
  },
  insight: {
    evidenceType: "学习片段与作品记录",
    timeRange: "最近 7 天",
    happened: "小宇最近反复探索星空和时间，也更常先说出自己的猜想。",
    seen: "这说明他正在练习把好奇心变成自己的问题和解释。",
    accompany: "找一个轻松的时刻，请他讲讲最近最想验证的猜想。",
  },
  action: {
    title: "睡前猜一猜：身体今晚会做什么？",
    lead: "用一个小问题，陪小宇把“休息”想成身体的主动安排。",
    opening: "你觉得身体睡着以后，会偷偷完成哪三件事？",
    steps: ["让孩子先说出三个猜想。", "一起挑一个猜想，补充身体恢复和整理记忆的例子。", "约定明天早上观察自己有什么变化。"],
    alternate: { title: "换个轻松的观察游戏", lead: "用一个小观察，陪孩子发现休息后的身体变化。", opening: "明早醒来，你觉得身体哪一处最先告诉你休息够不够？", steps: ["请孩子选一个身体信号。", "明早一起观察并描述变化。", "把发现画成一个小符号。"] },
  },
  weekend: {
    privacy: "profile-summary-only",
    primary: {
      label: "本周六 · 半天安排",
      title: "去城市自然博物馆，找一颗“会发光的石头”",
      lead: "把小宇最近关于星空和时间的好奇心，带到一个可以亲眼观察的地方。",
      reason: "小宇最近更常先说出自己的猜想，再去寻找答案；自然探索厅能让这个问题继续长出来。",
      place: "城市自然博物馆 · 自然探索厅",
      area: "室内 · 距家约 20 分钟",
      when: "周六 14:00–16:00",
      cost: "约 ¥60 / 家庭",
      prep: "带一张小纸条，记下孩子最想问的问题",
      tags: ["适合 10 岁", "室内", "半天"],
      opening: "你觉得这块石头从哪里来到地球？",
      steps: ["先让小宇选一件最想看的展品。", "请他记下一个猜想，再一起找展签里的证据。", "回家后用一句话讲讲：今天哪个答案最意外？"],
    },
    alternate: {
      label: "换一个 · 轻户外",
      title: "去附近公园做一场“影子计时”",
      lead: "不用准备复杂工具，用影子的变化陪小宇观察时间是怎样留下痕迹的。",
      reason: "小宇正在追问“时间怎么走”，影子是今天就能看见的答案。",
      place: "附近公园 · 开阔草地",
      area: "户外 · 约 60 分钟",
      when: "周日 15:30–16:30",
      cost: "免费",
      prep: "带手机或一支粉笔，注意天气变化",
      tags: ["适合 10 岁", "户外", "低成本"],
      opening: "如果我们每隔十分钟看一次，影子会去哪儿？",
      steps: ["找一根固定的树枝或路灯杆。", "每隔十分钟观察并描述影子变化。", "回家后猜一猜：明天同一时间会一样吗？"],
    },
  },
  course: {
    privacy: "profile-summary-only",
    month: "2026 年 9 月",
    title: "把好奇心变成自己的问题",
    subtitle: "给小宇的 4 周通识小旅程",
    reason: "这套课根据小宇的年龄、好奇心和最近更常提出猜想的学习线索组合。",
    profileTags: ["年龄 10 岁", "兴趣 星空", "性格 好奇", "喜欢先猜一猜"],
    stats: ["4 周", "6 节音频课", "图片随声音播放"],
    weeks: [
      {
        label: "第 1 周",
        title: "时间为什么会走？",
        focus: "观察与提问",
        lessons: [
          { id: "starlight", number: "01", title: "星光要走多久才到我们这里？", duration: "06:40", pageCount: 50, mentor: "猫头鹰老师", visual: "星空观察图", art: "starlight" },
          { id: "shadow-clock", number: "02", title: "影子会不会帮我们记时间？", duration: "07:10", pageCount: 44, mentor: "鼹鼠老师", visual: "影子计时图", art: "shadow" },
        ],
      },
      {
        label: "第 2 周",
        title: "答案从哪里来？",
        focus: "证据与表达",
        lessons: [
          { id: "question-map", number: "03", title: "把一个大问题拆成三小步", duration: "08:20", pageCount: 42, mentor: "鳄鱼爸爸", visual: "问题地图", art: "map" },
        ],
      },
      {
        label: "第 3 周",
        title: "如果答案不一样？",
        focus: "比较与判断",
        lessons: [
          { id: "moon-note", number: "04", title: "月亮每天都在变吗？", duration: "06:55", pageCount: 48, mentor: "猫头鹰老师", visual: "月相记录图", art: "moon" },
        ],
      },
      {
        label: "第 4 周",
        title: "把发现讲给别人听",
        focus: "复盘与表达",
        lessons: [
          { id: "time-capsule", number: "05", title: "给未来的自己留一段声音", duration: "09:00", pageCount: 40, mentor: "兔子老师", visual: "声音胶囊图", art: "capsule" },
          { id: "family-sky", number: "06", title: "和家人一起画一张天空地图", duration: "08:10", pageCount: 46, mentor: "鳄鱼爸爸", visual: "家庭共创图", art: "family" },
        ],
      },
    ],
  },
  examples: [
    {
      id: "empty-home",
      childName: "小宇",
      device: "Android Pad",
      data: { isExample: true, status: "empty" },
    },
    {
      id: "ready-home",
      childName: "小宇",
      device: "Android Pad",
      data: { isExample: true, status: "ready" },
    },
  ],
};
